export const MostPickedData = [
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 0,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 1,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 2,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 3,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 4,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 5,
  },
];

export const RecommendImages = [
  {
    categories: "Villa Canggu",
    title: "BlackSand Villa",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu.png",
    id: 0,
  },
  {
    categories: "Villa Canggu",
    title: "Pangi Gita",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu.png",
    id: 1,
  },
  {
    categories: "Villa Canggu",
    title: "Villa Kakatua",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu2.png",
    id: 2,
  },
  {
    categories: "Villa Canggu",
    title: "Villa Sungai",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu2.png",
    id: 3,
  },
  {
    categories: "Villa Canggu",
    title: "Villa Sabana",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu3.png",
    id: 4,
  },
  {
    categories: "Villa Canggu",
    title: "Villa Belong Dua",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu3.png",
    id: 5,
  },
  {
    categories: "Villa Canggu",
    title: "Villa Asmara",
    description: "Private villa with private pool",
    image: "./Gallery/Villa_Canggu4.png",
    id: 6,
  },
  {
    categories: "Hotel Canggu",
    title: "Canggu North",
    description: "Private villa with private pool",
    image: "./Gallery/Hotel_Canggu.png",
    id: 7,
  },
  {
    categories: "Hotel Canggu",
    title: "Kavya",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    id: 8,
  },
  {
    categories: "Hotel Kuta",
    title: "Grand Hyatt Bali",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 9,
  },
  {
    categories: "Hotel Kuta",
    title: "Ayana Resort",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 10,
  },
  {
    categories: "Hotel Kuta",
    title: "Padma Resort Legian",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 11,
  },
  {
    categories: "Hotel Kuta",
    title: "Seminyak Beach Resort",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 12,
  },
  {
    categories: "Hotel Kuta",
    title: "Villa Heights",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 13,
  },
  {
    categories: "Hotel Kuta",
    title: "Villa Sunset",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 14,
  },
  {
    categories: "Villa Kuta",
    title: "Villa Paradise",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 15,
  },
  {
    categories: "Villa Kuta",
    title: "Villa Serenity",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 16,
  },
  {
    categories: "Villa Kuta",
    title: "Villa Harmony",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 17,
  },
  {
    categories: "Hotel Sanur",
    title: "Fairmont Sanur Beach Bali",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 18,
  },
  {
    categories: "Hotel Sanur",
    title: "Sudamala Suites",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 19,
  },
  {
    categories: "Hotel Sanur",
    title: "Griya Santrian",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 20,
  },
  {
    categories: "Hotel Sanur",
    title: "Inna Grand Bali Beach",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 21,
  },
  {
    categories: "Villa Sanur",
    title: "Kejora Villas Suites",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 22,
  },
  {
    categories: "Villa Sanur",
    title: "Mahagiri Villas Sanur",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 23,
  },
  {
    categories: "Hotel NusaDua",
    title: "Grand Hyatt Bali",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    id: 24,
  },
  {
    categories: "Hotel NusaDua",
    title: "Ayodya Resort Bali",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 25,
  },
  {
    categories: "Villa NusaDua",
    title: "The Royal Santrian Luxury Beach Villas",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 26,
  },
  {
    categories: "Villa NusaDua",
    title: "Kayumanis Nusa Dua Private Villa & Spa",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 27,
  },
  {
    categories: "Villa NusaDua",
    title: "Royal Kamuela Villas & Suites at Nusa Dua",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 28,
  },
  {
    categories: "Villa NusaDua",
    title: "The Sakala Resort Bali",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 29,
  },
  {
    categories: "Villa NusaDua",
    title: "Villa Puri Tirta",
    description: "Private villa with private pool",
    image: "./images/recommend-img.png",
    id: 30,
  },
];
