export const MostPickedData = [
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 0,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 1,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 2,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 3,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 4,
  },
  {
    title: "Bali, Canggu",
    description: "Private villa with private pool",
    image: "./images/mostpicked_img.png",
    price: "3.500.000,00",
    star: "",
    wishlist: "",
    id: 5,
  },
];

export const RecommendImages = [
  {
    title: "Canggu",
    image: "./images/recommend-img.png",
    categories: "",
    id: 0,
  },
  {
    title: "Kuta",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 1,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 2,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 3,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 4,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 5,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 6,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 7,
  },
  {
    title: "Canggu",
    image: "./images/mostpicked_img.png",
    categories: "",
    id: 8,
  },
  {
    title: "Kuta",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 9,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 10,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 11,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 12,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 13,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 14,
  },
  {
    title: "",
    image: "./images/recommend-img.png",
    categories: "gunung",
    id: 15,
  },
];
